### ISSUE TITLE
【功能建议】是否有考虑迁移到Compose Multiplatform

### ISSUE THREAD

**Issue by Matcha-xiaobin** [jenly1314/UltraSwipeRefresh#10]
jetpack库似乎已经在往跨平台方向迁移了，大佬是否也考虑下迁移到跨平台？

**Comment by jenly1314** [comment]
> jetpack库似乎已经在往跨平台方向迁移了，大佬是否也考虑下迁移到跨平台？

你说的Jetpack库迁移似乎并没有看到确却的官方消息。`Compose Multiplatform` 与`Jetpack Compose`  虽写法类似，是因为`Compose Multiplatform` 中与平台无关的公共部分源码大多是来源于`Jetpack Compose` 。至于支持跨平台目前暂持观望态度。

**Comment by Matcha-xiaobin** [comment]
好的，期待未来的跨平台版本。

然后关于jitpack库往跨平台方向迁移的消息，是来自kotlin开发者公众号的一篇文章的消息，目前jetpack room已经有跨平台版本了：
[版本 2.7.0-alpha01](https://developer.android.com/jetpack/androidx/releases/room?hl=zh-cn#2.7.0-alpha01)
我也是通过这篇文章才知道这个库已经有跨平台版本了。

**Comment by vickyleu** [comment]
@Matcha-xiaobin 我已经处理好CMP的东西了,你可以试试用我的,不过没发maven,只用了github packages[UltraSwipeRefresh](https://github.com/vickyleu/UltraSwipeRefresh)

**Comment by Matcha-xiaobin** [comment]
> UltraSwipeRefresh

好的，后续有时间了会来试试
