### ISSUE TITLE
1.2.0崩溃

### ISSUE THREAD

**Issue by qiushui95** [jenly1314/UltraSwipeRefresh#13]
从1.1.3升级到1.2.0 app崩溃,项目中使用的compose版本为1.6.8.
实测将您的compose_bom更新为2024.06.00，demo也会崩溃。
应该是compose从1.5到1.6版本，将OverscrollConfiguration.kt 更名为OverscrollConfiguration.android.kt引起的，也就是1.2.0新增的contentContainer属性引起的崩溃

**Comment by jenly1314** [comment]
你可以通过修改全局配置来暂时解决此问题；配置示例：
```
UltraSwipeRefreshTheme.config = UltraSwipeRefreshTheme.config.copy(
    contentContainer = { it() },
)
```

**Comment by qiushui95** [comment]
我已经回退版本了，等你发1.2.1

**Comment by jenly1314** [comment]
> 我已经回退版本了，等你发1.2.1

不用回退，1.1.x版本在某些场景下会有其他问题，提供全局配置就是为了便于管理，就按我上面说的方式修改全局配置即可。（建议在`Application`的`onCreate`中调用）

**Comment by jenly1314** [comment]
> 从1.1.3升级到1.2.0 app崩溃,项目中使用的compose版本为1.6.8. 实测将您的compose_bom更新为2024.06.00，demo也会崩溃。 应该是compose从1.5到1.6版本，将OverscrollConfiguration.kt 更名为OverscrollConfiguration.android.kt引起的，也就是1.2.0新增的contentContainer属性引起的崩溃


重新详细的答复下这个问题，你可修改全局配置为与v1.2.0版本预期一致的配置

```kotlin
UltraSwipeRefreshTheme.config = UltraSwipeRefreshTheme.config.copy(
    contentContainer = { NoOverscrollEffect(it) },
)
```


关于`NoOverscrollEffect`具体可查看：[NoOverscrollEffect](https://github.com/jenly1314/UltraSwipeRefresh/blob/master/refresh/src/main/java/com/king/ultraswiperefresh/theme/UltraSwipeRefreshTheme.kt#L79-L83)
```kotlin
@Composable
@OptIn(ExperimentalFoundationApi::class)
private fun NoOverscrollEffect(content: @Composable () -> Unit) {
    CompositionLocalProvider(LocalOverscrollConfiguration provides null, content = content)
}
```

关于`NoOverscrollEffect` 存在的缘由可查看 [#7](https://github.com/jenly1314/UltraSwipeRefresh/issues/7#issuecomment-2172129823)；

既如此，下个版本可能不再向`OverscrollConfiguration`妥协了，考虑是否该移除内置的`NoOverscrollEffect`，交由使用的开发者自行决定是否需要`NoOverscrollEffect`。

**Comment by jenly1314** [comment]
已通过更新compose至v1.6.0来解决此问题；如需验证或优先使用可参见 [待发布版本](https://github.com/jenly1314/UltraSwipeRefresh/blob/master/test.md)

**Comment by qiushui95** [comment]
好的
