### ISSUE TITLE
上拉加载能否支持下滚到底部自动开始加载

### ISSUE THREAD

**Issue by MapleDS** [jenly1314/UltraSwipeRefresh#14]
目前的效果是滚动到底部后需要手动再上拉下才开始加载，能否支持下滚到底部不用上拉，自动就开始加载

**Comment by jenly1314** [comment]
> 目前的效果是滚动到底部后需要手动再上拉下才开始加载，能否支持下滚到底部不用上拉，自动就开始加载

`loadMoreTriggerRate` 参数你可以根据自己的需求配置，理论上调到足够小（比如：0.01f），就会自动触发加载。

**Comment by jenly1314** [comment]
https://github.com/jenly1314/UltraSwipeRefresh/issues/6
