### ISSUE TITLE
在錯誤的地方執行了刷新

### ISSUE THREAD

**Issue by LeonWeibyapps** [jenly1314/UltraSwipeRefresh#15]
https://github.com/jenly1314/UltraSwipeRefresh/assets/171216287/c1fef705-d79e-42cf-bb58-9f37aa44612b

根據影片，
如果我在內容中加入LazyColumn則會發生
當向上滑動動畫還沒停止時，向下拉，即便沒有在最上方仍會觸發更新。

**Comment by jenly1314** [comment]
你的前置条件是什么？代码怎么写的，完全未知，仅从视频能看出什么？
可使用：[演示App](https://raw.githubusercontent.com/jenly1314/UltraSwipeRefresh/master/app/release/app-release.apk) 来排查是否集成步骤问题。
