### ISSUE TITLE
下拉刷新里的布局是Column 无法触发下拉刷新

### ISSUE THREAD

**Issue by liutengsay1221** [jenly1314/UltraSwipeRefresh#16]
UltraSwipeRefresh里不用LazyColumn 用Column无法触发下拉刷新，这个需要怎么搞

**Comment by jenly1314** [comment]
> UltraSwipeRefresh里不用LazyColumn 用Column无法触发下拉刷新，这个需要怎么搞

使用`Column` 时需要加上 `Modifier.verticalScroll(rememberScrollState())`

**Comment by liutengsay1221** [comment]
好的，感谢
