### ISSUE TITLE
content只能是LazyColum吗？

### ISSUE THREAD

**Issue by GavinSong91** [jenly1314/UltraSwipeRefresh#18]

**Comment by jenly1314** [comment]
你想问的可能是这个：[#16](https://github.com/jenly1314/UltraSwipeRefresh/issues/16#issuecomment-2251788367)

**Comment by GavinSong91** [comment]
try try

**Comment by GavinSong91** [comment]
我是通过AndroidView调用ViewPager2，想给这个view加刷下加载。有啥思路吗？大佬

**Comment by jenly1314** [comment]
> 我是通过AndroidView调用ViewPager2，想给这个view加刷下加载。有啥思路吗？大佬

没太看懂你在说什么，水平滑动刷新？

**Comment by GavinSong91** [comment]
> > 我是通过AndroidView调用ViewPager2，想给这个view加刷下加载。有啥思路吗？大佬
> 
> 没太看懂你在说什么，水平滑动刷新？

在compose中调用Android的ViewPager2，实现类似抖音竖屏播放。AndroidView(factory = {context->ViewPager2(context)})
如果加了Modifier.verticalScroll(rememberScrollState())ViewPager2显示有问题，viewPager2也没有滑动事件了。

**Comment by jenly1314** [comment]
> > > 我是通过AndroidView调用ViewPager2，想给这个view加刷下加载。有啥思路吗？大佬
> > 
> > 
> > 没太看懂你在说什么，水平滑动刷新？
> 
> 在compose中调用Android的ViewPager2，实现类似抖音竖屏播放。AndroidView(factory = {context->ViewPager2(context)}) 如果加了Modifier.verticalScroll(rememberScrollState())ViewPager2显示有问题，viewPager2也没有滑动事件了。

compose中有`HorizontalPager` 和 `VerticalPager` ,  还要什么 `ViewPager2`；使用compose开发时，能用compose实现的就尽可能的少用AndroidView。
