### ISSUE TITLE
上拉静默加载配置

### ISSUE THREAD

**Issue by fanyafeng** [jenly1314/UltraSwipeRefresh#2]
是否支持类似RecycleView的静默加载，未滑动到底部已经开始加载更多

**Comment by jenly1314** [comment]
> 是否支持类似RecycleView的静默加载，未滑动到底部已经开始加载更多

这个是具体的业务了，跟刷新组件没多大关系吧；使用 `paging` 或许更适合这种业务场景。

**Comment by fanyafeng** [comment]
> > 是否支持类似RecycleView的静默加载，未滑动到底部已经开始加载更多
> 
> 这个是具体的业务了，跟刷新组件没多大关系吧；使用 `paging` 或许更适合这种业务场景。

嗯，改了下可以，不过在fling静默加载时会有卡顿
