### ISSUE TITLE
模拟器上运行，用鼠标滚轮进行滚动，会重复触发onRefresh和onLoadMore回调

### ISSUE THREAD

**Issue by zyizyiz** [jenly1314/UltraSwipeRefresh#20]
模拟器上运行，用鼠标滚轮进行滚动，会多次重复触发onRefresh和onLoadMore回调。用鼠标按住滚动则不会出现

**Comment by jenly1314** [comment]
> 模拟器上运行，用鼠标滚轮进行滚动，会多次重复触发onRefresh和onLoadMore回调。用鼠标按住滚动则不会出现

你的前置条件是什么？代码怎么写的？仅从简单的描述无法判断原因。
也可使用：[演示App](https://raw.githubusercontent.com/jenly1314/UltraSwipeRefresh/master/app/release/app-release.apk) 进行测试并验证是否集成步骤问题。
