### ISSUE TITLE
bug反馈，快速下拉抬起后，异常卡住不执行收起或刷新动画

### ISSUE THREAD

**Issue by suikastar** [jenly1314/UltraSwipeRefresh#21]
比较容易复现，复现成功了四五次

https://github.com/user-attachments/assets/62b909bf-bb8e-487b-80d0-ed878ee7a810

**Comment by jenly1314** [comment]
- 你发的视频貌似看不了。
- 我也一直在用的，没遇到你所说的问题；你需要提供更详细的信息便于复现问题（最好多测试几个不同Android版本的设备）。
- 改变 `state.isSwipeInProgress`的核心逻辑在[UltraSwipeRefreshNestedScrollConnection](https://github.com/jenly1314/UltraSwipeRefresh/blob/master/refresh/src/main/java/com/king/ultraswiperefresh/UltraSwipeRefreshNestedScrollConnection.kt)；你可以查看源码，了解详情；如果你有兴趣定位问题，可以通过观察`UltraSwipeRefreshState` 内部持有的一些值（包括 `isSwipeInProgress`但不限于），并打印相关日志来定位分析原因。

**Comment by suikastar** [comment]
@jenly1314 我的电脑和手机都能看这个视频，视频格式是h256，部分老设备可能不支持播放。

**Comment by suikastar** [comment]
@jenly1314 我是看了源码之后才提出的解决方案，并且解决了我的问题，但不知道在dispatchScrollDelta执行后重置isSwipeInProgress会不会带来其他问题。

**Comment by suikastar** [comment]
![Screenshot_2024-12-18-18-13-32-672_com android chrome](https://github.com/user-attachments/assets/ea58b25a-5455-49a0-b9ff-b09c50276ce6)
放张图，手指离开屏幕，就卡在这里不动了

**Comment by suikastar** [comment]
https://github.com/user-attachments/assets/9f45ce27-d43f-4e7f-b784-6f17e44105f7

重新转了个码，试试现在可能观看

**Comment by jenly1314** [comment]
> 396831797-62b909bf-bb8e-487b-80d0-ed878ee7a810.1.mp4 
> 重新转了个码，试试现在可能观看

这个视频可以看；按照视频的操作，复现问题了；我抽空定位下。

**Comment by suikastar** [comment]
@jenly1314 
} else if (state.indicatorOffset.roundToInt() == 0) {
            state.isSwipeInProgress = false
        }

估计是这块不完备，无法捕获所有情况

**Comment by jenly1314** [comment]
> @jenly1314 } else if (state.indicatorOffset.roundToInt() == 0) { state.isSwipeInProgress = false }
> 
> 估计是这块不完备，无法捕获所有情况

范围大概是在 [这一段](https://github.com/jenly1314/UltraSwipeRefresh/blob/1.3.0/refresh/src/main/java/com/king/ultraswiperefresh/UltraSwipeRefreshNestedScrollConnection.kt#L56-L104)；等有空时去定位了才知道。

**Comment by jenly1314** [comment]
已修复此问题；你可以下载最新的 [演示App](https://raw.githubusercontent.com/jenly1314/UltraSwipeRefresh/master/app/release/app-release.apk) 进行验证；如需直接使用，可参见：[待发布版本](https://github.com/jenly1314/UltraSwipeRefresh/blob/master/test.md)

**Comment by suikastar** [comment]
@jenly1314 已验证可用，所以当初是手滑了么，多给animateOffsetTo加了个判断

**Comment by jenly1314** [comment]
> @jenly1314 已验证可用，所以当初是手滑了么，多给animateOffsetTo加了个判断

并不是；没改之前的代码逻辑会看起来加更严谨；但定位问题时得出的结论是：当快速滑动时，虽然`state.isSwipeInProgress` 会发生了变更，但由于某种原因 [LaunchedEffect](https://github.com/jenly1314/UltraSwipeRefresh/blob/master/refresh/src/main/java/com/king/ultraswiperefresh/UltraSwipeRefresh.kt#L130) 会出现不执行的情况导致。改了代码之后；解决了问题；虽然 `animateOffsetTo` 可能会因为`LaunchedEffect`多调用一次，但不影响结果。

**Comment by suikastar** [comment]
@jenly1314 这个某种原因，是因为compose applyChanges机制导致的吗，同一个状态变化多次只会生效最后一次，快速滑动时，state.isSwipeInProgress变成true，又马上改成了false，在applyChanges看来一开始是false，现在还是false。所以LaunchedEffect没执行了，可不可以从这个角度修复bug呢？

**Comment by suikastar** [comment]
@jenly1314 

```
@Composable
fun LaunchedEffectExample() {
    var count by remember { mutableStateOf(0) }
    LaunchedEffect(count) {
        Log.e("LaunchedEffect", "Count: $count")
    }
    Column {
        Button(onClick = {
            count = count + 1
            count = count + 1
            count = count + 1
        }) {
            Text("点我+1")
        }

        Text("Count: $count")
    }
}
```

比如这样，LaunchedEffect只打印了“3”

**Comment by jenly1314** [comment]
> @jenly1314 这个某种原因，是因为compose applyChanges机制导致的吗，同一个状态变化多次只会生效最后一次，快速滑动时，state.isSwipeInProgress变成true，又马上改成了false，在applyChanges看来一开始是false，现在还是false。所以LaunchedEffect没执行了，可不可以从这个角度修复bug呢？

嗯，这个方向是对的；不过在没找到更好的修复方式之前，目前（修改后的代码）的这种解决方式就是最直接有效的。
