### ISSUE TITLE
isFinishing的状态问题

### ISSUE THREAD

**Issue by 465789287** [jenly1314/UltraSwipeRefresh#4]
我在使用中发现了一个问题，如果接口请求速度太快，isFinishing的状态变化就不会执行，finishDelayMillis对此也不生效

**Comment by jenly1314** [comment]
> 我在使用中发现了一个问题，如果接口请求速度太快，isFinishing的状态变化就不会执行，finishDelayMillis对此也不生效

好的，我抽空修复一下。

**Comment by jenly1314** [comment]
新发布的v1.1.1版本已修复此问题，可进行验证。
