### ISSUE TITLE
loadMoreEnabled = false后，下拉刷新的行为变得很奇怪

### ISSUE THREAD

**Issue by liu-xinhui** [jenly1314/UltraSwipeRefresh#8]
看视频，loadMore没禁用之前，下拉的部分会随着手指上下缩小，但是禁用之后，高度就不会缩小了，只会放大。

https://github.com/jenly1314/UltraSwipeRefresh/assets/7698511/e69b0050-9234-4d2e-8e03-1f1cd87ce88c

**Comment by jenly1314** [comment]
> 看视频，loadMore没禁用之前，下拉的部分会随着手指上下缩小，但是禁用之后，高度就不会缩小了，只会放大。
> 
>  666_1716433123.mp4

你要是昨天发现这个问题，我顺手就改了；我大概知道什么问题。后面抽空改。

**Comment by jenly1314** [comment]
已修改：如需验证，可参见：[待发布版本](https://github.com/jenly1314/UltraSwipeRefresh/blob/master/test.md)

**Comment by liu-xinhui** [comment]
可以了，感谢
