### ISSUE TITLE
发现一个小bug，就是国际化的时候，上次刷新时间那里会报错

### ISSUE THREAD

**Issue by liu-xinhui** [jenly1314/UltraSwipeRefresh#9]
`<string name="usr_last_refresh_time">上次刷新：MM-dd HH:mm</string>`
如果翻译成英文
`<string name="usr_last_refresh_time">Last refreshed：MM-dd HH:mm</string>`
程序就会崩溃。

**Comment by jenly1314** [comment]
> `<string name="usr_last_refresh_time">上次刷新：MM-dd HH:mm</string>` 如果翻译成英文 `<string name="usr_last_refresh_time">Last refreshed：MM-dd HH:mm</string>` 程序就会崩溃。

这是因为在使用`SimpleDateFormat` 格式化时间时，提供的格式中不能包含与时间格式无关的字母； 为了便于国际化，现已将时间格式资源拆开：`<string name="usr_time_format_pattern">MM-dd HH:mm</string>`

**Comment by liu-xinhui** [comment]
可以了
